on:
  push:
    branches:
      - main
jobs:
  trigger:
    uses: dspashynskyi/worklows/.github/workflows/flow1.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
    secrets:
      TEST_SECRET: ${{secrets.TEST_SECRET}}
